# Run `travis lint` when changing this file to avoid breaking the build.


# Use a larger VM as we run a lot of services
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

cache:
  directories:
  - $HOME/.m2

language: java

jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  # Manually install cassandra until https://github.com/travis-ci/travis-ci/issues/3952
  # See https://github.com/openzipkin/zipkin/issues/706
  - curl -SL http://downloads.datastax.com/community/dsc-cassandra-2.2.5-bin.tar.gz | tar xz
  - sed -i -e 's/INFO/WARN/g' dsc-cassandra-*/conf/logback.xml
  - sudo dsc-cassandra-*/bin/cassandra
  - sudo pip install ccm
  # install mysql schema
  - mysql -uroot -e 'SET GLOBAL innodb_file_format=Barracuda'
  - mysql -uroot -e 'create database if not exists zipkin'
  - mysql -uroot -Dzipkin < zipkin-storage/mysql/src/main/resources/mysql.sql
  # parameters used during a release
  - git config user.name "$GH_USER"
  - git config user.email "$GH_USER_EMAIL"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

  # Manually install elasticsearch until https://github.com/travis-ci/apt-source-whitelist/issues/190
  - curl -SL https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.2.1/elasticsearch-2.2.1.tar.gz | tar xz
  - elasticsearch-*/bin/elasticsearch -d > /dev/null

  # Manually install and run zk+kafka as it isn't an available service
  - curl -SL http://www.us.apache.org/dist/kafka/0.8.2.2/kafka_2.11-0.8.2.2.tgz | tar xz
  - nohup bash -c "cd kafka_* && bin/zookeeper-server-start.sh config/zookeeper.properties >/dev/null 2>&1 &"
  - nohup bash -c "cd kafka_* && bin/kafka-server-start.sh config/server.properties >/dev/null 2>&1 &"

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt BINTRAY_USER=your_github_account
  - secure: "HOptDMElLTHxuze2derex2ljpkZCJmlmod6Z5tIUDgQsJ+nmku2FAZ5Pxt66G4i9zrj3oIhNJ5HXDF04Hlm7DzfjKBvZXzzyusITyEf6TijOHsVD9o4ngcTnmVw7aP9Rd1Kh+FQPLpcxV8PbB0+BTmcFkQMxpjS/EgXYMDtv7Tcg+ALnGlVNHtf3EhwpxsCv5HBOp9+gw7Wta9aFCLWPySZUh/lf7WCHNnI48tBjujICQsuIp/A9RSHbFt1t0JbM99CT+Vei0gUSdIVKbQf4UcOl8uPty3nKyPc8P/4LDIxfX4acjy4jj7S2LUO77xVSMvisnHoQ/R0P3kmgl96avEtRIlC4Y4TV4PcYs8dmzX55T9zBQGVyt9IPK51XxKkZUQMlwduN5TvhHdkXW/bVELDGEZvFlhMpIjCdHZLcysVk+he+tnCo0Iv3nfVeLVCQ4qPLsumQy+Zl3l52hjvzcgdVrEwkZCl6kIfrkkLK2+srkPjoAK38uZhxEroSNgWGblCggbt/sNaqR2Z8yHT+uMlPSfOyADPr2Eufx0AgoWgFPvLO9a1nLNs5efMG3PFBFQSoBnCaOnrQ7j5NriKH0vWpuw6JpvTfl75VJ+PVb7qoDPOGCELgDJaL3Z8Uvb0CRbIo31/2JnY1m3gmQszUJNX2ej6oYCvWKrQW25b9+YI="
  # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "frm0I/rFFwKAfk3qzvebmSq2IQJt9l456AolnqX2biiOukDAVPNtT5kmXoPwfwemCjebXCO3Z3quPLXfsA2ZVah1WoeY8ICuTzGepg+E2FosOvl4/X5eCoNReyUG6nAqT/iNoQTCnSSDzFwh6+TciA7GPhftyBIFL8bohGscUWmtBYr/yha3LKE1weA3ahu4Kn4dswgkDtaD2fl4BsQVR2hsIQQxYOfpozspatJJtRuiVJne4f0rNdBdiQxinDh4d3B6yLjsGSFgIZ8G2dHVmlcyxmydmvX9pg30KulPM3r21qejt915k45rNRJN/IvVzGbLEaBCGIVvMS+S23Ih/Qfan41fFDekETV9bHo8IuZhxopNas/lymzA+YiXd3sId1kh8pifHBVdefrGP/5FL0bmsLOvwmY8h/hDOArTZgDgkFVaZP2NA0+W2YqlqY4JGwR/I/Jb0gDKFVOI9ScZCHCa0b7fQhWYOJry9PCmVIDv8nzByAjVncPxUEvj/hpQCG/R8D3ibFp4yLyARDWks/TF3VuiIbm/yhGg1/8p4lmx3Fj0ZvumU5x+deSVpzJK2TBVAfSTNbgsLFiLSMFSmKYK+r5vxRKoUPKFVx68VI4UQmibinNG9RE6Q0F/S0FnZnyPSEekt7os9Q9KoIovhMGii1WVSuB1Um1iypkt7zc="
  # Ex. travis encrypt GH_USER_EMAIL=for_github@domain.com --add
  - secure: "dMZHXaLDOYZsDeKECqvukrKK9ToAiHiZWgwBueVG9MYcI/LP56PEB5KS64iCh1AUBqp8xcSaf41xP7hl/9Jl2PLok6XFob2FathGFJnyaMr4m9EUAiq3bN9sYorS7XGQ/ZfMJiAOM9ipzogQGY1gMDWsa5kCZu0qIwmXpxnpUp9E35l0KPKScLY5O6y/Pi8wfLMu0fWtyAxGDQIkUWqSQWaz5yNS2aPK8tOJFmD6/ekV9QOxQXj1Cx+vhWzeuJAmknSb47A8UuaguG4PqsaF3Ww5TwohORt/5GvRZmGBeeU4yWpS5Q5Zi8dMUIO6r+uzCkiAarxajf23oHX3cGPyqsAE8tJvf425SlD982VQon6g08t4JBeAlWEE6hJeM/a1gMTsy/2WtVP3ql2wNt7LHVAayMjjBgsRMmwaRAkUrckwirxkaJVmqj/bfA5s8zYyjKdtyc+f9KLmwkWJ9Em2adAG86BB5lZrcXcneoLNLrmN5WKs00LLskNVYcfdOAs97AUq6ZY1U7koDluUtX50qELa6Yzc+pxB1Jvy9ZGaJtg6FqfxWhEj+qe2nBLZa9mTD2mCBUcIGEFh4m67Ql0yFCKTl7sZuuTbeLmkIASy+M8ENfd7IXgBbLQX+iin+55xQEb5hxRWiPHWB6mYNW1gE1lx7O/bW1GDB1H0TG8Sw14="
  # Ex. travis encrypt GH_USER=your_github_account --add
  - secure: "dFvQkGjZDQpPCMsJU5K5+CQWZYSWkN2b2XBpXTNu9fQc22nQb5alxNYGx/YwE9JsMP4Dxh3Ros0gh3sB1F3bbIMsFvhkbablnYm3uJiHszbOt9hwBPAqeddS+kgT6admBSYNE2b9Zhb0vRlWPs/dSO9NQ0pEIhFDtcZgZ2Q+0F1p0nACR2rPwqYKmSMR2LTQDTZrPPxAsNx2a2gnGZWxQJe2tl5mgX5j/EBC+HKef9txn0n5AIUsFhzNposGMOE0iNDg/eGcbG7LCmyx6EazlDSAvbmJBZd7Hho3snGvnroqm1yFo1ry2Rlg2W+rsiy7o38Ng5j8oLjYcpejQJwgPMdIA2wM1GUHb+Dg7UebzWocrVwGMv91nS5+VcCZ4/mvK5bOI0VRyMB8TwI5mlcmqwIDmd/pbdYbpJKwsEARaHEPT1s1t8SL1plrFdCthnEcEUwT7LyvubgDPsLcwzODsmyuKrK+aUvZWU7U5o8/XqEMy6cDHb1Fu4qjVbpOchonsvlCOO1CP9cIAkMhNmT5Pvp/oL/c7rov0JpUuexdPwi9NtgJ0uUcBIoU17v/2erK3NNssj98oKLPuhXBwl60bEEFsx0+TyI4tcwPXS8+PuWHUzewmcFHzUVIK7hclRMHdbdY6L0/C42VoVvkp+FEl5Ycihi4O6uLnv3I4Z42lH8="
  # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "Iu7X1ePNpk6rbIse4P2EFu9f8I8mVMjZqFXaoIiosNuOh2V3VsyKWb/+m0oQdUPquzw5N9POjbhERE2ICAI+9o4Zkb4rjXXLHhvAEvvy9NLpH9dB2/AsMxWXha/UHmCHwq4z9qSWsOA0G0kx2FzTbUUN4PKQQjIWrUInbZpjWdIZhDVRpp2j5ZIYFrn0DS9piYIWJgfwdkCSq0c8Gpd5XxxHik/Fkb4W/UfRCM1gCNB/eagqiATyd7Eg8WnKp1lVwdipbrre7nosT2hcIILdyAnsbwd0ByMGIBnzJcFf/ITnSQQEZqRLP0401ZWmwSniSbpxvwi+jc2YVfTXqRF6GvEMWVx0b8QJoMlsQDXqv04ZpHPU2lQu2pUca4vM42KYYjNfVI91w5EgEkQEUZzBQs+zaRoT3kwpIehUHlNZNu7+uKKt3iapZ6oVSpa5i+4YDYMC92I0smRAq662xjmGusZFYwPXA9+f5Qa2XtxJnYmxBir1kq+I2Tdiy8mM7tKSbog/S7oKtS4M5znNd4ygp3ikzCHw/oZvZxjYO8S+2ds8XrzP9F0EWHOtiwwmRcH6QBjlC/I+lf1CbLIfJwPCHeqSIUZFqbwWdJ7LJsRBzFY48yfvtSDe4kYaeXrESc7KtYtqMhjzEUFt3+Md061yJZmVvz0wn3G/wUAQEbwyvZI="
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
  - secure: "h8Tn3hrh5Z2GSh9rpMilh8i3p5moZp/FhiqYM771aIdIeiQ0r8Pa0eOl52E2UpJyFF/x1+45T/fev3MhApRWyduaUeBsd44IuTXzXYoh5YqTOPb9AJ0i5TisN5aL9zc+8JDC7dxfBIASKP5sngJi3ZcAenQ6Lzf+74YMvmaSkxIwEPb7NgpfakE1dHp9c1Yx3MTRXptBnY3Bs28LD+PdD+wX89/1aMc4hP+fRgMlJzlLMLv2RYLTDlsiGbrBkSy9odWqnjWoColz9VTFNSIH/sboe6dHvl84pP96svrZu1h7/IDCuSdBuqzmYBlVPCrD7OP+BXBFcbHntKa6joz26U+G7aIJfzcA1Z3+AOg1bgiKe3PuqPBpZdkyoGmRSd9tNTBFoPYv2MbeOFOGcS5KrYdbqCLz10vg5v9Pej3+GUabg/VoH86EyScZC/hRrdSPz3uK0wajE8RreAmsTjqe2g94YQqwMm6Dt7rIo1jY2L1dTBcuAIv0nNSZlKFFqYee7QsUSaZ+DxqmWpZ60CBoNns5L6uocev19dXXEuivVrxnnxk9RhJVosXUR+dZflAwrdj/t4Rk98Y4yi6fT75Y2WVBoYPBpQwvEV8lF4VH3LE6GYT21nnwqkpdrATnTM/U1VU33oJEpk03Q9idikEfK3tDJORPtC9PfYumIvXsi8A="
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
  - secure: "QBUqmsuLqd9+O1HQF0b0MibcMwuyVjKfHZbC9g55vvVC8FSJlFqBuRVWUhLdDD1qJcEIt/24VKjwWZ5YxnerJ7RKG6iDF5IzgccrH2FTvhPHaSFHhZu/JbkC25V4dtK27qLZQGX3WEXrYuWSch42ZRgCqvcsW7PmjoNN+/Rqoy7KxSVGXKh3+NAtn/pz7NBWxqEq0jF7h4BX+VHiUD1gH4jr+Lhg9pyVZ1c9CPz6uujjzXSFpiUY17eugA1elfNPqqVE2LR3qA/qdawRlx/QO5pomu2xBM1eFewH6XTUjsev8nC8YP3uXeyeu3sW8wSAFwfF5+DTMvoALQipV9GD4VBpDdgFU7TndKa3EwCro3sj/40Jmpo6vIxyjV+vSu7QbHUzc4JzAHTceVUXrkhTuvYSiVFxuMsGYOfqIB/T80ohcWvxPCGq4pt0QkryLP/YE4A9ernA4YwrHi0CdgaqO5P4i+fXvh2BUiOe7kBS4KfVHfLq+blgDUqXsBUKYX7k7MK9AkNkgKxkUFlLQinBr6TS9OoVsEI2GIIejs1ZjfllOFoCwdMhhqxGKhzrnHvfgXwnKj6CkkdRsk6fqzf4PLe5zw5GMOhWtZs9uvNf3S6rm0AXafEe2DhTbyKgK5XunMmZaEydk6APfraCqYrCAwkd1u8golLnmbOj27UYvMQ="

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/637e968b45032d16ee26
    on_success: change
    on_failure: always
    on_start: false
